---

- name: Install docker-engine 1.12.5
  hosts: docker_hosts
# You can change hosts to "all" or your group as it is 
# listed in /etc/ansible/hosts
  remote_user: centos
  become: true

# You can change remote_user to root and omit "become: true"
# if you are logging in as root

  roles:
    - docker_engine
